# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/16849257-400c-46c5-aea3-9d4dc1496e46";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2975-DDCC";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  # fileSystems."/export/zfs" =
  #   { device = "tank/terminaldogma";
  #     fsType = "zfs";
  #   };

  # fileSystems."/tank" =
  #   { device = "tank";
  #     fsType = "zfs";
  #   };

  # fileSystems."/mnt/secondbranch" =
  #   { device = "tank/terminaldogma/secondbranch";
  #     fsType = "zfs";
  #   };

  swapDevices = [
    {device = "/dev/disk/by-uuid/a3cc36e7-ca45-4b5a-bc67-cecdc57af1ea";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
